x-base: &base
  image: fastapi-celery:latest
  volumes:
    - ./app:/app

services:
  base_builder:
    build:
      context: .
      dockerfile: Dockerfile
    <<: *base

  fastapi:
    <<: *base
    container_name: fastapi
    command: >
      sh -c "uv sync && . .venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    <<: *base
    container_name: celery
    command: > 
      sh -c "uv sync && . .venv/bin/activate && celery -A package.workers.controller worker --loglevel=info"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  flower:
    <<: *base
    container_name: flower
    command: >
      sh -c "uv sync && . .venv/bin/activate && celery -A package.workers.controller flower --port=5555"
    ports:
      - "5556:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - fastapi
      - celery
      - redis
